### ISSUE TITLE
Remove domains command

### ISSUE THREAD

**Issue by pacodes** [guumaster/hostctl#5]
Proposing add subcommands:
- remove domains [-p profile] [-all] - will remove by name in profile (-p) or hosts file (-all)
- remove ip [-p profile] [-all] - will remove by IP in profile (-p) or hosts file (-all)

**Comment by guumaster** [comment]
I'm ok with that subcommand as long as follow some ideas I had when creating the tool:

- **'default' profile shouldn't be touched by `hostctl`**. It should only manage profiles created with the tool.
- **all domains in a profile should have the same IP**, if you need different IP, create a new profile

The second idea is not enforced yet because the parser is too simple, but at some point it should.
